/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Item: typeof import('./../../views/Components/Sidebar/Item.vue')['default']
    ItemGroup: typeof import('./../../views/Components/Sidebar/ItemGroup.vue')['default']
    Sidebar: typeof import('./../../views/Components/Sidebar.vue')['default']
    Sidebar2: typeof import('./../../views/components/Sidebar2.vue')['default']
    UtilityBar: typeof import('./../../views/Components/UtilityBar.vue')['default']
  }
}
